version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile.web
    container_name: django_web
    volumes:
      - static_volume:/app/static
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
    env_file:
      - .env
    networks:
      - portal_net
      
  nginx:
    image: nginx:alpine
    container_name: django_nginx
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - static_volume:/app/static
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portal_net

volumes:
  static_volume:

networks:
  portal_net:
