version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile.web
    container_name: portal_web
    volumes:
      - static_volume:/app/static
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
    env_file:
      - .env
    networks:
      - portal_net
      
  nginx:
    image: nginx:alpine
    container_name: portal_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portal_net

  mongodb:
    image: mongo:latest
    container_name: portal_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    env_file:
      - .env    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - portal_net
      
volumes:
  static_volume:

networks:
  portal_net:
