version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: portal_backend/Docker/Dockerfile_django
    container_name: portal_django
    expose:
      - "8000"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    networks:
      - portal_net
    depends_on:
      - redis
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL_PROD}
    container_name: portal_frontend
    expose:
      - "3001"
    depends_on:
      - django
    networks:
      - portal_net
  nginx:
    build:
      context: .
      dockerfile: portal_nginx/Dockerfile
    container_name: portal_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./portal_nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
      - frontend
    networks:
      - portal_net
  celery:
    build:
      context: .
      dockerfile: portal_backend/Docker/Dockerfile_celery
    container_name: portal_celery
    command: /app/start.sh
    volumes:
      - ./portal_backend/Docker/celery_start.sh:/app/start.sh
      - ./portal_backend:/portal_backend
    env_file:
      - .env
    depends_on:
      - django
      - redis
    networks:
      - portal_net
  mongodb:
    image: mongo:7.0
    container_name: portal_mongodb
    volumes:
      - ./portal_backend/data/mongodb:/data/db
      - ./portal_backend/entrypoint-mongo.sh:/entrypoint.sh:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    entrypoint: ["/entrypoint.sh"]
    networks:
      - portal_net

  redis:
    image: redis:7-alpine
    container_name: portal_redis
    networks:
      - portal_net

volumes:
  static_volume:

networks: 
  portal_net:
