FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    libkrb5-dev \
    build-essential \
 && pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir gunicorn \
 && apt-get purge -y --auto-remove build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY . .

RUN apt-get update && apt-get install -y dos2unix

COPY portal_backend/Docker/entrypoint.sh /entrypoint.sh
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh

EXPOSE 8000

CMD ["/entrypoint.sh"]